import type { NextPage } from 'next'
import Head from 'next/head'

import { attributes, react as HomeContent } from '../content/home.md'

import styles from '../styles/Home.module.css'

import { Category } from '../types/cms'

import { Categories } from '../components/categories'

const Home: NextPage = () => {
    const { title, categories } = attributes as { title: string; categories: Array<Category> }

    return (
        <div className={styles.container}>
            <Head>
                <title>RESPECT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h1>{title}</h1>
                    <HomeContent />
                    Our services:
                    <Categories categories={categories} />
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    )
}

export default Home
