import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { attributes, react as HomeContent } from '../content/home.md'

import styles from '../styles/Home.module.css'
import { Cat } from '../types/cats'

type Props = {
    user: User
}

type User = {
    id: number
    email: string
    first_name: string
    last_name: string
    avatar: string
}

export const getStaticProps: GetStaticProps<Props> = async () => {
    const res = await fetch('https://reqres.in/api/users/2')
    const user: User = await res.json()

    if (!user) {
        return {
            notFound: true,
        }
    }

    return {
        props: { user },
    }
}

const Home: NextPage<Props> = ({ user }) => {
    const { title, cats } = attributes
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <article>
                    <h1>{title}</h1>
                    <HomeContent />
                    <ul>
                        {(cats as Array<Cat>).map((cat, k) => (
                            <li key={k}>
                                <h2>{cat.name}</h2>
                                <p>{cat.description}</p>
                            </li>
                        ))}
                    </ul>
                </article>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
